// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Mat3 {
    pub m_11: f32,
    pub m_12: f32,
    pub m_13: f32,
    pub m_21: f32,
    pub m_22: f32,
    pub m_23: f32,
    pub m_31: f32,
    pub m_32: f32,
    pub m_33: f32,
}

impl __sdk::InModule for Mat3 {
    type Module = super::RemoteModule;
}
