// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct OnConnectArgs {}

impl From<OnConnectArgs> for super::Reducer {
    fn from(args: OnConnectArgs) -> Self {
        Self::OnConnect
    }
}

impl __sdk::InModule for OnConnectArgs {
    type Module = super::RemoteModule;
}

pub struct OnConnectCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `on_connect`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait on_connect {
    /// Request that the remote module invoke the reducer `on_connect` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_on_connect`] callbacks.
    fn on_connect(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `on_connect`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`OnConnectCallbackId`] can be passed to [`Self::remove_on_on_connect`]
    /// to cancel the callback.
    fn on_on_connect(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> OnConnectCallbackId;
    /// Cancel a callback previously registered by [`Self::on_on_connect`],
    /// causing it not to run in the future.
    fn remove_on_on_connect(&self, callback: OnConnectCallbackId);
}

impl on_connect for super::RemoteReducers {
    fn on_connect(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("on_connect", OnConnectArgs {})
    }
    fn on_on_connect(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> OnConnectCallbackId {
        OnConnectCallbackId(self.imp.on_reducer(
            "on_connect",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::OnConnect {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_on_connect(&self, callback: OnConnectCallbackId) {
        self.imp.remove_on_reducer("on_connect", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `on_connect`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_on_connect {
    /// Set the call-reducer flags for the reducer `on_connect` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn on_connect(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_on_connect for super::SetReducerFlags {
    fn on_connect(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("on_connect", flags);
    }
}
