// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::physics_world_type::PhysicsWorld;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PhysicsStepWorldArgs {
    pub world: PhysicsWorld,
}

impl From<PhysicsStepWorldArgs> for super::Reducer {
    fn from(args: PhysicsStepWorldArgs) -> Self {
        Self::PhysicsStepWorld { world: args.world }
    }
}

impl __sdk::InModule for PhysicsStepWorldArgs {
    type Module = super::RemoteModule;
}

pub struct PhysicsStepWorldCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `physics_step_world`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait physics_step_world {
    /// Request that the remote module invoke the reducer `physics_step_world` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_physics_step_world`] callbacks.
    fn physics_step_world(&self, world: PhysicsWorld) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `physics_step_world`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PhysicsStepWorldCallbackId`] can be passed to [`Self::remove_on_physics_step_world`]
    /// to cancel the callback.
    fn on_physics_step_world(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &PhysicsWorld) + Send + 'static,
    ) -> PhysicsStepWorldCallbackId;
    /// Cancel a callback previously registered by [`Self::on_physics_step_world`],
    /// causing it not to run in the future.
    fn remove_on_physics_step_world(&self, callback: PhysicsStepWorldCallbackId);
}

impl physics_step_world for super::RemoteReducers {
    fn physics_step_world(&self, world: PhysicsWorld) -> __sdk::Result<()> {
        self.imp
            .call_reducer("physics_step_world", PhysicsStepWorldArgs { world })
    }
    fn on_physics_step_world(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &PhysicsWorld) + Send + 'static,
    ) -> PhysicsStepWorldCallbackId {
        PhysicsStepWorldCallbackId(self.imp.on_reducer(
            "physics_step_world",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PhysicsStepWorld { world },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, world)
            }),
        ))
    }
    fn remove_on_physics_step_world(&self, callback: PhysicsStepWorldCallbackId) {
        self.imp.remove_on_reducer("physics_step_world", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `physics_step_world`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_physics_step_world {
    /// Set the call-reducer flags for the reducer `physics_step_world` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn physics_step_world(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_physics_step_world for super::SetReducerFlags {
    fn physics_step_world(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("physics_step_world", flags);
    }
}
