// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::vec_3_type::Vec3;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PhysicsWorld {
    pub id: u64,
    pub ticks_per_second: f32,
    pub time_step: f32,
    pub sub_step: u32,
    pub gravity: Vec3,
    pub precision: f32,
    pub position_iterations: u32,
    pub debug: bool,
}

impl __sdk::InModule for PhysicsWorld {
    type Module = super::RemoteModule;
}
