// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::collider_type::Collider;
use super::transform_type::Transform;
use super::vec_3_type::Vec3;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RigidBody {
    pub id: u64,
    pub world_id: u64,
    pub transform: Transform,
    pub velocity: Vec3,
    pub force: Vec3,
    pub mass: f32,
    pub collider: Collider,
    pub inv_mass: f32,
    pub restitution: f32,
    pub friction: f32,
    pub is_sleeping: bool,
    pub sleep_timer: f32,
}

impl __sdk::InModule for RigidBody {
    type Module = super::RemoteModule;
}
