// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::collider_type::Collider;
use super::friction_type::Friction;
use super::mat_3_type::Mat3;
use super::quat_type::Quat;
use super::restitution_type::Restitution;
use super::rigid_body_type_type::RigidBodyType;
use super::vec_3_type::Vec3;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RigidBody {
    pub id: u64,
    pub world_id: u64,
    pub position: Vec3,
    pub rotation: Quat,
    pub linear_velocity: Vec3,
    pub angular_velocity: Vec3,
    pub force: Vec3,
    pub mass: f32,
    pub inv_mass: f32,
    pub collider: Collider,
    pub inertia_tensor: Mat3,
    pub inv_inertia_tensor: Option<Mat3>,
    pub torque: Vec3,
    pub friction: Friction,
    pub restitution: Restitution,
    pub pre_solve_linear_velocity: Vec3,
    pub pre_solve_angular_velocity: Vec3,
    pub previous_position: Vec3,
    pub previous_rotation: Quat,
    pub body_type: RigidBodyType,
}

impl __sdk::InModule for RigidBody {
    type Module = super::RemoteModule;
}
